name: mind_tracker
description: A new Flutter application.


publish_to: 'none'

version: 1.0.0+1


environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: "^2.0.5"
  firebase_core: "^1.0.2"
  firebase_auth: "^1.0.1"
  cloud_firestore: "^1.0.3"
  qr_flutter: "^4.0.0"
  barcode_scan_fix: ^1.0.2

  flutter_calendar_carousel: ^1.5.3

  charts_flutter: ^0.10.0

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.8.1


flutter_icons:
  image_path: "assets/mindtracker_icon.png" 
  android: true
  ios: true

flutter:
  
  assets:
  - assets/meditation.gif
  - assets/meditation_3.gif
  uses-material-design: true