name: mind_tracker
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1


environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^0.5.4+8
  shared_preferences_web: ^0.1.0
  firebase_core: ^0.5.3
  firebase_analytics: ^6.3.0
  firebase_auth: ^0.18.4+1
  cloud_firestore: ^0.14.4
  qr_flutter: "^4.0.0"
  barcode_scan_fix: ^1.0.2
  rxdart: ^0.26.0
  flutter_bloc: ^7.0.0
  equatable: ^2.0.0
  fluttertoast: ^8.0.6

  flutter_calendar_carousel: ^1.5.3


  #charts_flutter 0.10.0
  charts_flutter: ^0.10.0

  intl: ^0.16.1
  flutter_typeahead: ^2.0.0



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flutter_local_notifications: ^4.0.1+2
  flutter_native_timezone: ^1.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.8.1


flutter_icons:
  image_path: "assets/logo_dark.png" 
  android: true
  ios: true

flutter:
  
  assets:
  - assets/meditation.gif
  - assets/meditation_3.gif
  - assets/logo.jpg
  - assets/logo.png
  - assets/logo_dark.png
  uses-material-design: true